# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.8
_src_path: https://github.com/jupyterlab/extension-template
author_email: zephyr.dassouli@imt-atlantique.net
author_name: zephyr
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyter-dvre
project_short_description: A jupyter DVRE extension
python_name: jupyter_dvre
repository: ''
test: false

